---
title: "Homework"
output: 
  rmarkdown::html_vignette:
    fig_caption: yes
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{Syllabus}
  %\VignetteEncoding{UTF-8}
---

# Homework 1


<div class="alert alert-info">
  <strong>Important:</strong> To submit your homework share your GitHub repository with **stephaneguerrier** and **munsheet** by the deadline (i.e. 09/14/17 at 4PM).  Do not modify your homework after the deadline. We will grade the most recent (~ 4PM) portion of your RMarkdown file. 
</div>


The objectives of this homework assignment are the following

- Build your own RMarkdown document; 
- Master different aspects of RMarkdown syntax;
- Become familiar with GitHub as collaborative tool.

To start, create a (perferably private) GitHub repository for your group, and name it **stat297hw1**. Once again, make sure to add **munsheet** and **stephaneguerrier** as collaborators. This project **must** be done using GitHub and respect the following requirements:

- All members of the group must `commit` at least once. 
- All commit messages must be reasonably `clear` and `meaningful`.   
- Your GitHub repository much include at least one `issue` containing some form of TO DO list. 

In your repository create a file called \textbf{HW1.Rmd} providing an HTML output with the theme `cerulean` and syntax highlighting `tango`. This file should contain the following elements:

1. A "title" section which should *at least* include:
    - A title (e.g. Homework 1) 
    - The authors 
    - The date (think of using `Sys.time()`)

2. A section called "Introduction" where you provide a short summary of the structure of your homework. Moreover, record a short video to introduce your group and include it in your R Markdown document.

3. A section called "Group Members". This sections should have one sub-section for each group member in your team. For example, a group with three members should have three biographies in total. Each of these sub-sections (named after each group member) should include small biographies containing *at least* the following elements:

    - A picture of your choice (preferably of yourself). Make sure to include a caption for this image. 
    -  A paragraph describing your favorite hobby as well as one interesting fact about yourself.
    - Your favorite quote in blockquote format and be sure to reference your quote using BibTex.
    - A table having two columns (first column containing the classes you are following this semester; second column containing the time of these classes).

4. A section called "R Markdown Syntax", where you will demonstrate your R Markdown skills! In this section make sure to: 

    - Show an example where the chunk option `cache = T` leads to a misleading answer. This example must be different from the one presented in the textbook.
    - Simulate 100 random samples from a standard normal distribution using the function `rnorm()`. Store these 100 values in a vector called `x`. Then, compute the empirical median, mean and variance of `x`. Are these results different from 0, 0 and 1 (their respective theoretical values)? Is this result surprising? Justify your answer. 
    - Include a graph showing the histogram of `x` (make sure to include a caption to this figure), this can be done in R using the function `hist()`.
    - Include the equation below: 
\[
	\begin{aligned}
			 \mathbb{E} \left[ \text{var} \left\{
                             \boldsymbol{v}_1\left(
                               \hat{\boldsymbol{\theta}},n\right) \big|
                             \hat{\boldsymbol{\theta}} \right\}  \right] 
&=
                         \text{var} \left\{ \mathbf{v}_1\left(
                             \boldsymbol{\theta}_0,n\right)  \right\}  +
                         \mathbb{E} \left[\mathcal{O}_p\left\{
{\bf D}_1(\boldsymbol{\theta}^*,n)(\hat{\boldsymbol{\theta}} - \boldsymbol{\theta}_{0}), 
\dots,
{\bf D}_p(\boldsymbol{\theta}^*,n)(\boldsymbol{\theta} - \boldsymbol{\theta}_{0})
\right\}\right]\\
			&= \text{var} \left\{ \mathbf{v}_1\left( \boldsymbol{\theta}_0,n\right)  \right\}  + \mathcal{O}\left(n^{-2}\right).
	\end{aligned}
\]

    - Include the following *in-line* equation: $\mathbf{A} \equiv \left[a_{i,j}\right]_{i,j = 1, \ldots, p}$.
    - Include the following text in blue\textbf{blue}: <font color="blue">"Vérité dans un temps, erreur dans un autre.", Charles de Montesquieu</font>
    - Include a "More info" button with hide/unhide functionality such as:
    <button data-toggle="collapse" data-target="#demo">More info</button>
<div id="demo" class="collapse">
Some additional info... :)
</div> 
    - Include a "color box" such as the one below:
    
    <div class="alert alert-success">
  <strong>Some important Info:</strong> something
</div>

5. A "References" section that contains all the references used in your document.
