---
title: 'RMarkdown Playground'
bibliography: biblio.bib
output: html_document
---

Experiment with the Rmd Code below and test output.

Here are some examples: @harrar2013taste ; [see also @harrar2011there].

# Header Type 1
## Header Type 2 
### Header Type 3

* an asterisk starts an unordered list
* and this is another item in the list
+ or you can also use the + character
- or the - character

To start an ordered list, write this:

1. this starts a list *with* numbers
2. this will show as number '2.'
33. a wrong number here still shows as number '3.'
#. the '#' continues the list and shows as number '4.'
9. any number or '#' will keep the list going.
    * just indent by 4 spaces (or tab) to make a sub-list
        1. keep indenting for more sub lists
    * here i'm back to the second level

Use * or _ to emphasize things:

*this is in italic*  and _so is this_

**this is in bold**  and __so is this__

***this is bold and italic***  and ___so is this___

+---------------+---------------+--------------------+
| Fruit         | Price         | Advantages         |
+===============+===============+====================+
| *Bananas*     | $1.34         | - built-in wrapper |
|               |               | - bright color     |
+---------------+---------------+--------------------+
| Oranges       | $2.10         | - cures scurvy     |
|               |               | - **tasty**        |
+---------------+---------------+--------------------+

> Use the > character in front of a line, *just like in email*.
> Use it if you're quoting a person, a song or whatever.
 >>Add the >> if you want to quote within a quote.

**Links Full:** <https://google.com/>

**Links Custom:** [RMarkdown Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf)



# References
