---
title: "Semester Project"
output: 
  rmarkdown::html_vignette:
    fig_caption: yes
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{Syllabus}
  %\VignetteEncoding{UTF-8}
---

# Project Proposal 

Your semester project is meant to showcase what you have learned in this class. You should choose a topic that you find interesting but that is also reasonable to complete within the scope of the class. Each project must respect the following criteria:

1) Propose a new statistical/visualization tool for an application you are interested in. 
2) Involve a significant amount for programming done by all members of the group.
3) Have fun doing it.

The output of your project will be:

1) An awesome project!
2) A well documented GitHub repository (see e.g. https://github.com/SMAC-Group/ds)
3) A website showcasing your work (think of adding a video) used as a github page (see e.g. https://smac-group.github.io/stat297/)
4) An R package that be installed directly from GitHub (such as the `stat297` package which can be installed as `devtools::install_github("SMAC-Group/stat297")`)
5) A shiny app to allow someone having absolutely no R knowledge to "use" what you have done in your project.

To make sure that your project is suitable we will organize a project proposal presentation on **October 12th, 2017**. This will be 5 minutes presentation (make sure you respect that!) where you should try to "sell" your project to the class. This presentation can be in any form but you should address the following points:

1) **Problem / Topic**: What problem or topic are you addressing? Why is it worth doing? Will you be able to use the project as a way to demonstrate your R savvy-ness (e.g. to future employers, application to grad school)?

2) **Idea**: What is your idea for addressing the problem or topic? Why is it original relative to prior work? Where did the idea come from?

3) **Feasibility**: Is this project able to be completed before the end of the semester? What steps must occur to complete the project before the end of the semester?
